config/routes.rb
Rails.application.routes.draw do
  resources :task_infos do
    collection do
      get 'task_status_change'
    end
  end
  resources :task_info_logs, :only => [:create, :update]
  resources :task_categories, :only => [:new, :create]

  namespace :task_db_http_request do
    resources :task_infos do
      collection do
        get 'read_reminder'
        post 'upload_comment'
      end
    end
  end

  resources :game_genres
  resources :game_infos do
    collection do
      get 'switch_by_platform'
      get 'register_new_controller_manual'
      get 'register_new_game_action_form'
      get 'register_new_game_action'
    end
  end

  namespace :admin do
    get 'task_db', to: 'task_dbs#index'
    get 'task_db/resave_task_infos', to: 'task_dbs#resave_task_infos'
  end

  get 'twitters', to: 'twitters#index'
  get 'twitters/get_home_timeline', to: 'twitters#get_home_timeline'
  get 'twitters/post_tweet_by_get', to: 'twitters#post_tweet_by_get'
  post 'twitters/post_tweet', to: 'twitters#post_tweet'
  get 'twitters/python', to: 'twitters#python'
  get 'twitters/parse_sentence', to: 'twitters#parse_sentence'

end

app/models/game_genre.rb
class GameGenre < ActiveRecord::Base
#  attr_accessible :name_jp, :name_en

  has_and_belongs_to_many :game_infos

end

app/controllers/game_genres_controller.rb
class GameGenresController < ApplicationController
  before_action :set_game_genre, only: [:show, :edit, :update, :destroy]

  # GET /game_genres
  # GET /game_genres.json
  def index
    @game_genres = GameGenre.all
  end

  # GET /game_genres/1
  # GET /game_genres/1.json
  def show
  end

  # GET /game_genres/new
  def new
    @game_genre = GameGenre.new
  end

  # GET /game_genres/1/edit
  def edit
  end

  # POST /game_genres
  # POST /game_genres.json
  def create
    @game_genre = GameGenre.new(game_genre_params)

    respond_to do |format|
      if @game_genre.save
        format.html { redirect_to @game_genre, notice: 'Game genre was successfully created.' }
        format.json { render :show, status: :created, location: @game_genre }
      else
        format.html { render :new }
        format.json { render json: @game_genre.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /game_genres/1
  # PATCH/PUT /game_genres/1.json
  def update
    respond_to do |format|
      if @game_genre.update(game_genre_params)
        format.html { redirect_to @game_genre, notice: 'Game genre was successfully updated.' }
        format.json { render :show, status: :ok, location: @game_genre }
      else
        format.html { render :edit }
        format.json { render json: @game_genre.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /game_genres/1
  # DELETE /game_genres/1.json
  def destroy
    @game_genre.destroy
    respond_to do |format|
      format.html { redirect_to game_genres_url, notice: 'Game genre was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_game_genre
      @game_genre = GameGenre.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def game_genre_params
      params.require(:game_genre).permit(:name_jp, :name_en)
    end
end

app/helpers/game_genres_helper.rb
module GameGenresHelper
end

app/views/game_genres/_form.html.erb
<%= form_for(@game_genre) do |f| %>
  <% if @game_genre.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@game_genre.errors.count, "error") %> prohibited this game_genre from being saved:</h2>

      <ul>
      <% @game_genre.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name_jp %><br>
    <%= f.text_field :name_jp %>
  </div>
  <div class="field">
    <%= f.label :name_en %><br>
    <%= f.text_field :name_en %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/game_genres/edit.html.erb
<h1>Editing Game Genre</h1>

<%= render 'form' %>

<%= link_to 'Show', @game_genre %> |
<%= link_to 'Back', game_genres_path %>

app/views/game_genres/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Game Genres</h1>

<table>
  <thead>
    <tr>
      <th>Name jp</th>
      <th>Name en</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @game_genres.each do |game_genre| %>
      <tr>
        <td><%= game_genre.name_jp %></td>
        <td><%= game_genre.name_en %></td>
        <td><%= link_to 'Show', game_genre %></td>
        <td><%= link_to 'Edit', edit_game_genre_path(game_genre) %></td>
        <td><%= link_to 'Destroy', game_genre, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Game genre', new_game_genre_path %>

app/views/game_genres/new.html.erb
<h1>New Game Genre</h1>

<%= render 'form' %>

<%= link_to 'Back', game_genres_path %>

app/views/game_genres/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name jp:</strong>
  <%= @game_genre.name_jp %>
</p>

<p>
  <strong>Name en:</strong>
  <%= @game_genre.name_en %>
</p>

<%= link_to 'Edit', edit_game_genre_path(@game_genre) %> |
<%= link_to 'Back', game_genres_path %>