config/routes.rb
Rails.application.routes.draw do
  resources :task_infos do
    collection do
      get 'task_status_change'
    end
  end
  resources :task_info_logs, :only => [:create, :update]
  resources :task_categories, :only => [:new, :create]

  namespace :task_db_http_request do
    resources :task_infos do
      collection do
        get 'read_reminder'
        post 'upload_comment'
      end
    end
  end

  resources :game_genres
  resources :game_infos do
    collection do
      get 'switch_by_platform'
      get 'register_new_controller_manual'
      get 'register_new_game_action_form'
      get 'register_new_game_action'
    end
  end

  namespace :admin do
    get 'task_db', to: 'task_dbs#index'
    get 'task_db/resave_task_infos', to: 'task_dbs#resave_task_infos'
  end

  get 'twitters', to: 'twitters#index'
  get 'twitters/get_home_timeline', to: 'twitters#get_home_timeline'
  get 'twitters/post_tweet_by_get', to: 'twitters#post_tweet_by_get'
  post 'twitters/post_tweet', to: 'twitters#post_tweet'
  get 'twitters/python', to: 'twitters#python'
  get 'twitters/parse_sentence', to: 'twitters#parse_sentence'

end

app/models/task_info.rb
class TaskInfo < ActiveRecord::Base

  belongs_to :estimate_task_time_type, :class_name => "TaskTimeType"
  belongs_to :task_status
  belongs_to :task_category
  has_many :task_info_logs, :autosave => true

  before_save :before_save_callback

  def before_save_callback
    self.task_status_id = TaskStatus.task_status_not_started.id if self.task_status_id == nil
    self.task_category_id = TaskCategory.task_category_undefined.id if self.task_category_id == nil
  end

  # タスク経過時間を計算
  def calc_task_time
    if task_status_id == TaskStatus.task_status_finish.id && 
      real_task_time != nil && real_task_time != 0
      return real_task_time
    end
    if task_status_id == TaskStatus.task_status_abort.id && 
      real_task_time != nil && real_task_time != 0
      return real_task_time
    end
    return 0 if task_status_id == TaskStatus.task_status_not_started.id
    return 0 if task_start_time == nil # 仕様追加時の暫定対応
    calc_val = (Time.now() - task_start_time).to_i / 60
    calc_val += real_task_time if real_task_time != nil
    return calc_val
  end

  # 想定進捗率を%で計算
  def calc_estimate_progress
    return 0 if estimate_task_time_type == nil
    return (100.0 * calc_task_time / estimate_task_time_type.value).round
  end
end

app/controllers/task_db_http_request/task_infos_controller.rb
class TaskDbHttpRequest::TaskInfosController < ApplicationController

  protect_from_forgery with: :null_session

  # テスト用
  def new
=begin
    task_info = TaskInfo.find_by(:task_category_id => TaskCategory.task_category_test.id)
    task_info.detail = "スクリプトからのPostテスト"
    task_info.detail = params[:detail] if params[:detail]!= nil
    task_info.save
=end

    require 'yaml'
    respond_to do |format|
      format.html { render :text => params.to_yaml }
    end
  end

  def create
    task_info = TaskInfo.find(params[:id])

    if task_info == nil
      respond_to { |format| format.html { render :text => "failed" } }
      return false
    end

    task_info_log = nil
    if params[:task_info_logs] != nil && params[:task_info_logs][:content] != nil
      if params[:task_info_logs][:id] == nil
        task_info_log = TaskInfoLog.create(:task_info_id => params[:id])
      else
        task_info_log = TaskInfoLog.find(params[:task_info_logs][:id])
      end
      task_info_log.content = params[:task_info_logs][:content]
    end

    if task_info_log == nil
      respond_to { |format| format.html { render :text => "failed" } }
      return false
    end

    if task_info_log.new_record?
      task_info.task_info_logs << task_info_log
      task_info.save
    else
      task_info_log.save
    end

    respond_to do |format|
      format.html { render :text => "success" }
    end
  end

  # GET
  # リマインダフラグを立てる
  def read_reminder
    task_info_id = params[:task_info_id]
    task_info = TaskInfo.find(task_info_id)

    task_info.read_reminder = true
    msg = task_info.save ? "success" : "failed"
    respond_to do |format|
      format.html { render :text => msg }
    end
  end

  # POST
  # アップロードコメントをTaskDBに送信
  def upload_comment
    task_info = TaskInfo.find(params[:id])
    task_info_log = TaskInfoLog.new(:content => params[:upload_comment], :log_type => TaskInfoLog.type_text)
    msg = ""

    if task_info == nil
      msg = "TaskInfo not found(id:#{params[:id]})"
    elsif params[:upload_comment] == nil
      msg = "Params should have upload comment."
    else
      task_info.task_info_logs << task_info_log
      msg = "success" if task_info.save
    end

    respond_to do |format|
      format.html { render :text => msg }
    end
  end

end

app/controllers/task_infos_controller.rb
class TaskInfosController < ApplicationController
  before_action :set_task_info, only: [:show, :edit, :update, :destroy, :task_status_change]

  # GET /task_infos
  # GET /task_infos.json
  def index
#    @task_infos = TaskInfo.all
    @view_status_name = params[:view_status_name]
    if @view_status_name == nil || @view_status_name == ""
      @task_infos = TaskInfo.includes(:task_status).where("task_status_id not in (#{TaskStatus.task_status_finish.id})")
    else
      @task_infos = TaskInfo.includes(:task_status).where("task_status_id in (#{TaskStatus.find_by(:name_jp => @view_status_name).id})")
    end

    @view_category_name = params[:view_category_name]
    view_category = TaskCategory.find_by(:name_jp => @view_category_name)
    if view_category != nil
      @task_infos = @task_infos.where(:task_category_id => view_category.id)
    end

    respond_to do |format|
      format.html
      format.xml {
        task_info_xmls = @task_infos.map { |c|
          {
            :task_info => c, 
            :add_info => {:estimate_progress => c.calc_estimate_progress}
          }
        }
        render :xml => task_info_xmls
      }
    end
  end

  # GET /task_infos/1
  # GET /task_infos/1.json
  def show
    respond_to do |format|
      format.html
      format.xml { render :xml => @task_info }
    end
  end

  # GET /task_infos/new
  def new
    @task_info = TaskInfo.new
  end

  # GET /task_infos/1/edit
  def edit
  end

  # POST /task_infos
  # POST /task_infos.json
  def create
    @task_info = TaskInfo.new(task_info_params.merge(:task_status_id => TaskStatus.task_status_not_started.id))

    respond_to do |format|
      if @task_info.save
        format.html { redirect_to @task_info, notice: 'Task info was successfully created.' }
        format.json { render :show, status: :created, location: @task_info }
      else
        format.html { render :new }
        format.json { render json: @task_info.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /task_infos/1
  # PATCH/PUT /task_infos/1.json
  def update
    respond_to do |format|
      if @task_info.update(task_info_params)
        format.html { redirect_to @task_info, notice: 'Task info was successfully updated.' }
        format.json { render :show, status: :ok, location: @task_info }
      else
        format.html { render :edit }
        format.json { render json: @task_info.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /task_infos/1
  # DELETE /task_infos/1.json
  def destroy
    @task_info.destroy
    respond_to do |format|
      format.html { redirect_to task_infos_url, notice: 'Task info was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  # PUT /task_infos/1/task_status_change
  def task_status_change
    if @task_info.task_status_id != params[:task_status_id]
      # タスク時間計測周り
      case params[:task_status_id].to_i
      when TaskStatus.task_status_not_started.id then
        @task_info.real_task_time = 0
      when TaskStatus.task_status_start.id then
        @task_info.task_start_time = Time.now()
      when TaskStatus.task_status_abort.id then
        @task_info.real_task_time = @task_info.calc_task_time
      when TaskStatus.task_status_finish.id then
        @task_info.real_task_time = @task_info.calc_task_time
      end

      @task_info.task_status_id = params[:task_status_id] # real_task_timeの更新計算自体は前のステータスでないとだめなのでステータス更新はこのタイミング
      task_info_log = TaskInfoLog.new(:content => "進捗を#{@task_info.task_status.name_jp}に変更", :task_info_id => @task_info.id)
      @task_info.task_info_logs << task_info_log
    end
    msg = @task_info.save ? "Task status changed" : "Task status change process failed"
    respond_to do |format|
      format.html { 
        redirect_to @task_info.task_status_id == TaskStatus.task_status_finish.id ? task_infos_path : task_info_path(@task_info), notice: msg
      }
      format.json { head :no_content }
    end
  end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_task_info
      @task_info = TaskInfo.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def task_info_params
      params.require(:task_info).permit(:title, :detail, :estimate_task_time_type_id, :task_category_id)
    end
end

app/helpers/task_infos_helper.rb
module TaskInfosHelper
end

app/views/task_infos/_form.html.erb
<%= form_for(@task_info) do |f| %>
  <% if @task_info.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@task_info.errors.count, "error") %> prohibited this task_info from being saved:</h2>

      <ul>
      <% @task_info.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title, "タイトル" %><br>
    <%= f.text_field :title, :maxlength => 100 %>
  </div>
  <div class="field">
    <%= f.label :detail, "詳細" %><br>
    <%= f.text_area :detail, :size => "120x4", :maxlength => 200 %>
  </div>
  <div class="field">
	<% # @fixme selectの第１引数をtask_infosにするなら第２引数は実際にあるaccessorでないとだめらしい %>
	<%= select "task_info", "estimate_task_time_type_id", TaskTimeType.all().order("value").map{ |c| [c.name_jp, c.id] }, {}, {:id => "estimate_time_select"} %>
  </div>
  <div class="field">
	<%= select "task_info", "task_category_id", TaskCategory.all().map{ |c| [c.name_jp, c.id] }, {:include_blank => true}, {:id => "task_category_select"} %>
	<%= button_tag type: 'button', onclick: "window.open('#{new_task_category_path}?is_open_from_other=true', 'カテゴリー追加', 'width=500,height=400')" do %>
		<%= "カテゴリー追加" %>
	<% end %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/task_infos/_task_info_table.html.erb
<!--
	border:表の外の線の太さ
	cellpadding:セル中の文字と枠の間隔
	cellspacing:セルとセルの間の線の太さ
-->
<table border="2" cellpadding="5" cellspacing="0">
  <caption><h3><%= table_caption %></h3></caption>
  <thead>
    <tr style="background:#ccccff">
      <th>タイトル</th>
	  <th>詳細</th>
	  <th>進捗</th>
	  <th colspan="3">時間(見積もり/経過/想定進捗率)</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% task_infos.each do |task_info| %>
      <tr>
        <td width="25%"><div id="title_div"><%= link_to task_info.title, task_info_path(task_info), :id => "title_link" %></div></td>
		<td width="40%"><%= task_info.detail %></td>
		<% task_status = TaskStatus.find_by(:id => task_info.task_status_id) %>
		<td width="10%", id='show_task_status'><%= task_status != nil ? task_status.name_jp : "" %></td>
		<% task_time = task_info.estimate_task_time_type %>
		<td width="5%"><%= task_time != nil ? task_time.name_jp : "" %></td>
		<td width="5%"><%= task_time != nil ? "#{task_info.calc_task_time}分" : "" %></td>
		<td width="5%"><%= task_time != nil ? "#{task_info.calc_estimate_progress}%" : "" %></td>
        <td width="5%"><%= link_to 'Edit', edit_task_info_path(task_info) %></td>
        <td width="5%"><%= link_to 'Destroy', task_info, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/task_infos/edit.html.erb
<h1>Editing Task Info</h1>

<%= render 'form' %>

<%= link_to 'Show', @task_info %> |
<%= link_to 'Back', task_infos_path %>

app/views/task_infos/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Task Infos</h1>

<!-- javascript -->
<script type="text/javascript">
<!--
// 絞り込みオプションが選択されたらリロード[TaskStatus]
function reload_page_by_status(){
	window.location.href = "<%= task_infos_path %>?view_status_name=" + $("#view_status_select").val() + "&view_category_name=<%= @view_category_name %>";
}

// 絞り込みオプションが選択されたらリロード[TaskCategory]
function reload_page_by_category(){
	window.location.href = "<%= task_infos_path %>?view_status_name=<%= @view_status_name %>&view_category_name=" + $("#view_category_select").val();
}
-->
</script>

<p>進捗状況で絞り込み
<%= select "", "", TaskStatus.all.map { |c| ["#{c.name_jp}のみ表示", c.name_jp] }, {:include_blank => true, :selected => @view_status_name}, {:onchange => "reload_page_by_status()", :id => "view_status_select"} %>
</p>

<p>カテゴリで絞り込み
<%= select "", "", TaskCategory.all.map { |c| ["#{c.name_jp}", c.name_jp] }, {:include_blank => true, :selected => @view_category_name}, {:onchange => "reload_page_by_category()", :id => "view_category_select"} %>
</p>

<!-- 
タイトル内容を検索してリストをリアルタイム表示
アルファベットはリアルタイムに絞り込めるけど
@fixme 全部の要素入れるで処理重そう
-->
<input type="search" name="name" autocomplete="on" list="title_search_list" id="title_search">
<datalist id="title_search_list">
<% TaskInfo.all.each do |task_info| %>
	<option value="<%= task_info.title %>"><%= task_info_url(task_info) %></option>
<% end %>
</datalist>
<script type="text/javascript">
<!--
	$('#title_search').on('input', function(){
		var options = $('datalist#title_search_list')[0].options
		for( var i=0; i<options.length; i++){ 
			if( options[i].value == $(this).val() ){
				window.location.href = options[i].innerHTML;
			}
		}
	});
-->
</script>
<p>

</p>

<%
	task_category = TaskCategory.find_by(:name_jp => @view_category_name)
	task_categories = task_category == nil ? TaskCategory.all : [task_category]

	task_status = TaskStatus.find_by(:name_jp => @view_status_name)
	task_statuses = task_status == nil ? TaskStatus.all.order("view_priority DESC") : [task_status]
%>
<% task_categories.each do |task_category| %>
	<h2 id="task_category_name"><%= task_category.name_jp %></h2>
	<% task_statuses.each do |task_status| %>
		<%
			task_infos_partial = @task_infos.where(:task_status_id => task_status.id).where(:task_category_id => task_category.id)
			next if task_infos_partial.blank?
		%>
		<br>
		<%= render partial: 'task_info_table', locals: {task_infos: task_infos_partial, table_caption: task_status.name_jp} %>
		<br>
	<% end %>
<% end %>

<br>

<%= link_to 'New Task info', new_task_info_path %>

app/views/task_infos/new.html.erb
<h1>New Task Info</h1>

<%= render 'form' %>

<%= link_to 'Back', task_infos_path %>

app/views/task_infos/show.html.erb
<%= hidden_field_tag :page_file_name, File.basename(__FILE__) %>

<p id="notice"><%= notice %></p>

<p>
  <strong>タイトル:</strong><br>
  <%= @task_info.title %><br>

  <strong>詳細:</strong><br>
  <%= @task_info.detail.gsub(/\r\n|\r|\n/, "<br>").html_safe %><br>

  <strong>リマインダ既読:</strong><%= check_box @task_info, :read_reminder, { :checked => @task_info.read_reminder, :disabled => true } %>
</p>

<!-- 進捗変更ボタン -->
<% task_status_change_url = "task_status_change" %>
<!-- 前のステータスに変更 -->
<% prev_status = @task_info.task_status.prev_task_status %>
<% if prev_status != nil %>
<%= form_tag(task_status_change_url, :method => 'get') do %>
	<div class="actions">
	  <%= hidden_field_tag :id, @task_info.id, { :id => "task_status_change_prev" } -%>
	  <%= hidden_field_tag :task_status_id, prev_status.id %>
	  <%= submit_tag "#{prev_status.name_jp}に変更する", { :id => "task_status_change_prev_button" } %>
	</div>
<% end %>
<% end %>

<!-- 次のステータスに変更 -->
<% next_status = @task_info.task_status.next_task_status %>
<% if next_status != nil %>
<%= form_tag(task_status_change_url, :method => 'get') do %>
	<div class="actions">
	  <%= hidden_field_tag :id, @task_info.id, { :id => "task_status_change_next" } -%>
	  <%= hidden_field_tag :task_status_id, next_status.id %>
	  <%= submit_tag "#{next_status.name_jp}に変更する", { :id => "task_status_change_next_button" } %>
	</div>
<% end %>
<% end %>

<p>
<%
   estimate_task_time = @task_info.estimate_task_time_type != nil ? @task_info.estimate_task_time_type.name_jp : -1
   task_time = @task_info.calc_task_time
   task_time_str = "#{task_time}分"
   estimate_progress = @task_info.calc_estimate_progress
%>
<strong>想定進捗率:<%= "#{estimate_progress}%"  %> 経過時間:<%= task_time_str %> 見積もり時間:<%= estimate_task_time %></strong>
</p>

<%
   task_info_log_width = 120
%>

<!-- 新規作業メモ追加欄 -->
<% task_info_log = TaskInfoLog.new(:task_info_id => @task_info.id) %>
<%= form_for(task_info_log, :url => task_info_logs_path(task_info_log)) do |f| %>
	<div class="field">
	  <%= f.hidden_field :task_info_id %>
	  <%= f.label :content, "作業メモ" %><br>
	  <%= f.text_area :content, { :id => "task_info_log_content", :size => "#{task_info_log_width.to_s}x4", :maxlength => 200 } %><br>
	</div>
	<div class="actions">
	  <%= f.select :log_type, [["メモ", "text"], ["画像", "picture"]] %>
	  <%= f.submit "作業メモ追加", { :id => "create_task_info_log_button" } %>
	</div>
<% end %>

<br>
<br>

<!-- 作業メモ表示 -->
<script type="text/javascript">
<!--

var update_form_tag = $("<form></form>").attr({/*"action" : "/task_info_logs", */"accept-charset" : "UTF-8", /*"data-remote" : "true",*/ "method" : "post"}).append($("<input></input>").attr({"type" : "submit", "name" : "commit", "value" : "更新"})).append($("<input></input>").attr({"type" : "hidden", "name" : "_method", "value" : "patch"}));
var update_tag = $("<span></span>").attr({id: "update_log"}).append(update_form_tag);
//var update_tag = $("<span></span>").attr({id: "update_log"}).append($("<a></a>").attr({"href" : "javascript:alert('aa')"}).text("更新"));

var restore_form_tag = $("<form></form>").attr({"action" : "/task_info_logs", "accept-charset" : "UTF-8", "data-remote" : "true", "method" : "put"}).append($("<input></input>").attr({"type" : "submit", "name" : "commit", "value" : "戻す"}));
var restore_tag = $("<span></span>").attr({id: "restore_log"}).append(restore_form_tag);
//var restore_tag = $("<span></span>").attr({id: "restore_log"}).append($("<a></a>").attr({"href" : "javascript:alert('bb')"}).text("戻す"));

function showTaskInfoLogUi(log_id)
{
	var helper_tag = $("div#show_task_info_log_helper_" + log_id);
	if( helper_tag.find("span#update_log")[0] == undefined ){
		update_form_tag.attr("action", "/task_info_logs/" + log_id);

		$("#update_log").remove();
		$("#restore_log").remove();
		helper_tag.append(update_tag).append(restore_tag);
	}
}

function hideTaskInfoLogUi()
{
//	$("#update_log").remove();
//	$("#restore_log").remove();
}
-->
</script>
<% task_info_logs = TaskInfoLog.where(:task_info_id => @task_info.id).order("created_at DESC") %>
<% task_info_logs.each do |task_info_log| %>
<% if task_info_log.is_type_text %>
	<% row = (task_info_log.content.length*1.5 / task_info_log_width).to_i + (task_info_log.content.lines.size) + 2 # 少し余計にバッファとっておく %>
	<%
	   text = task_info_log.content
	   show_task_info_log_ui = "showTaskInfoLogUi(#{task_info_log.id})"
	   hide_task_info_log_ui = "hideTaskInfoLogUi()"
	%>
	<% if false %>
	<%= text_area_tag task_info_log, text, { :id => "show_task_info_log_#{task_info_log.id}", :size => "#{task_info_log_width.to_s}x#{row.to_s}", :maxlength => 200, :onclick => show_task_info_log_ui, :onBlur => hide_task_info_log_ui } %><br>
	<% end %>
	<%= form_for(task_info_log, {:method => 'put', :remote => 'true'}) do |f|%>
<%= text_area_tag "task_info_log[content]", text, { :id => "show_task_info_log_#{task_info_log.id}", :size => "#{task_info_log_width.to_s}x#{row.to_s}", :maxlength => 200 } %><br>
		<%= f.submit "更新", {:id => "task_info_log_update_#{task_info_log.id}"} %>
		<%= f.submit "戻す", {:id => "task_info_log_restore_#{task_info_log.id}"} %>
	<% end %>
<% else %>
	<%= image_tag task_info_log.content %>
<% end %>
	<div style='color:#777777' id="show_task_info_log_helper_<%= task_info_log.id %>">ID:<%= task_info_log.id %> 作成:<%= task_info_log.created_at %> 更新:<%= task_info_log.updated_at %></div>
<br>
<% end %>

<%= link_to 'Edit', edit_task_info_path(@task_info) %> |
<%= link_to 'Back', task_infos_path %>