config/routes.rb
Rails.application.routes.draw do
  resources :task_infos do
    collection do
      get 'task_status_change'
    end
  end
  resources :task_info_logs, :only => [:create, :update]
  resources :task_categories, :only => [:new, :create]

  namespace :task_db_http_request do
    resources :task_infos do
      collection do
        get 'read_reminder'
        post 'upload_comment'
      end
    end
  end

  resources :game_genres
  resources :game_infos do
    collection do
      get 'switch_by_platform'
      get 'register_new_controller_manual'
      get 'register_new_game_action_form'
      get 'register_new_game_action'
    end
  end

  namespace :admin do
    get 'task_db', to: 'task_dbs#index'
    get 'task_db/resave_task_infos', to: 'task_dbs#resave_task_infos'
  end

  get 'twitters', to: 'twitters#index'
  get 'twitters/get_home_timeline', to: 'twitters#get_home_timeline'
  get 'twitters/post_tweet_by_get', to: 'twitters#post_tweet_by_get'
  post 'twitters/post_tweet', to: 'twitters#post_tweet'
  get 'twitters/python', to: 'twitters#python'
  get 'twitters/parse_sentence', to: 'twitters#parse_sentence'

end

app/models/game_info.rb
class GameInfo < ActiveRecord::Base
#  attr_accessible :name_jp, :name_en
#  attr_accessible :game_genre_id

  validates :name_jp, presence: true, length: { maximum: 30 }
  validates :name_en, format: { with: /\A[\d\w]*\z/ }

  has_and_belongs_to_many :game_genres
  has_and_belongs_to_many :game_platforms
  validates :game_platforms, presence: true
  has_many :game_key_configs, :autosave => true
end

app/controllers/game_infos_controller.rb
class GameInfosController < ApplicationController
  before_action :set_game_info, only: [:show, :edit, :update, :destroy]

  # GET /game_infos
  # GET /game_infos.json
  def index
    @game_infos = GameInfo.all
  end

  # GET /game_infos/1
  # GET /game_infos/1.json
  def show
  end

  # GET /game_infos/new
  def new
    @game_info = GameInfo.new
  end

  # GET /game_infos/1/edit
  def edit
    @is_register_new_controller_manual = false
  end

  # POST /game_infos
  # POST /game_infos.json
  def create
    @game_info = GameInfo.new(:name_jp => game_info_params[:name_jp], :name_en => game_info_params[:name_en])
    @game_info = update_game_genres(params[:game_info])
    @game_info = update_game_platforms(params[:game_info])
#    @game_info = update_game_key_configs(params[:game_info])

    respond_to do |format|
      if @game_info.save
        format.html { redirect_to @game_info, notice: 'Game info was successfully created.' }
        format.json { render :show, status: :created, location: @game_info }
      else
        format.html { render :new }
        format.json { render json: @game_info.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /game_infos/1
  # PATCH/PUT /game_infos/1.json
  def update
    @game_info = update_game_genres(params[:game_info])
    @game_info = update_game_platforms(params[:game_info])
    @game_info = update_game_key_configs(params[:game_info])

    respond_to do |format|
      if @game_info.save
        format.html { redirect_to @game_info, notice: 'Game info was successfully updated.' }
        format.json { render :show, status: :ok, location: @game_info }
      else
        format.html { render :edit }
        format.json { render json: @game_info.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /game_infos/1
  # DELETE /game_infos/1.json
  def destroy
    @game_info.destroy
    respond_to do |format|
      format.html { redirect_to game_infos_url, notice: 'Game info was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def switch_by_platform
    @game_info = GameInfo.find(params[:id])
    @current_platform = GamePlatform.find_by(:name_en => params[:platform])
    render
  end

  # 新しい操作方法登録
  def register_new_controller_manual
    @game_info = GameInfo.find(params[:id])
    @game_platform_id = params[:game_platform_id]

#    redirect_to "/game_infos/#{@game_info.id}/edit"
#    render
  end

  # 新規アクション登録フォーム
  def register_new_game_action_form
    render 'register_new_game_action_form'
  end

  def register_new_game_action
    @game_action = GameAction.find_or_create_by(:name_en => params[:name_en], :name_jp => params[:name_jp])
    @is_success = @game_action.save
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_game_info
      @game_info = GameInfo.find(params[:id])
    end

    def update_game_genres(genre_params)
      return @game_info if genre_params[:game_genre_ids] == nil

      # 追加
      genre_params[:game_genre_ids].each { |game_genre_id|
        game_genre = GameGenre.find_by(:id => game_genre_id)
        next if game_genre == nil
        next if @game_info.game_genres.include?(game_genre)
        @game_info.game_genres << game_genre
      }

      # 削除
      @game_info.game_genres.each { |game_genre|
        next if genre_params[:game_genre_ids].include?(game_genre.id.to_s)
        @game_info.game_genres.delete(game_genre)
      }

      return @game_info
    end

    def update_game_platforms(platform_params)
      return @game_info if platform_params[:game_platform_ids] == nil

      # 追加
      platform_params[:game_platform_ids].each { |game_platform_id|
        game_platform = GamePlatform.find_by(:id => game_platform_id)
        next if game_platform == nil
        next if @game_info.game_platforms.include?(game_platform)
        @game_info.game_platforms << game_platform
      }

      # 削除
      @game_info.game_platforms.each { |game_platform|
        next if platform_params[:game_platform_ids].include?(game_platform.id.to_s)
        @game_info.game_platforms.delete(game_platform)
      }

      return @game_info
    end

    def update_game_key_configs(key_config_params)
      return @game_info if key_config_params[:game_key_config_infos] == nil

      key_config_params[:game_key_config_infos].each { |game_key_config_info|
        game_platform_id = game_key_config_info.delete(:game_platform_id)
        next if game_platform_id.to_i < 0

        game_key_config = GameKeyConfig.find_or_create_by(:game_platform_id => game_platform_id, :game_info_id => @game_info.id)

        game_key_config_info.each { |key, value|
          next if value == ""

          game_key = GameKey.find_or_create_by(:game_key_type_id => key.to_i, :game_action_id => value.to_i)
          game_key.save if game_key.new_record?

          # 同じキータイプの場合は入れ替え
          is_exist_same_key_type = false
          game_key_config.game_keys.each_with_index { |current_game_key, idx|
            # ボタンタイプが違う場合は特になにもしない
            next if current_game_key.game_key_type_id != game_key.game_key_type_id
            is_exist_same_key_type = true
            game_key_config.game_keys[idx] = game_key
          }

          game_key_config.game_keys << game_key if is_exist_same_key_type == false
        }

        # 新規KeyConfigの場合は追加
        if game_key_config.new_record?
          @game_info.game_key_configs << game_key_config
        end

        game_key_config.save
      }

      return @game_info
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def game_info_params
      # キーにモデルと同一名は使えないみたい(ex. :game_key_configs)
      params.require(:game_info).permit(:name_jp, :name_en, :game_genre_ids => [], :game_platform_ids => [], :game_key_config_infos => [:game_platform_id])
    end
end

app/helpers/game_infos_helper.rb
module GameInfosHelper
end

app/views/game_infos/_form.html.erb
<%= form_for(@game_info) do |f| %>
  <% if @game_info.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@game_info.errors.count, "error") %> prohibited this game_info from being saved:</h2>

      <ul>
      <% @game_info.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name_jp, "日本語名" %><br>
    <%= f.text_field :name_jp %>
  </div>
  <div class="field">
    <%= f.label :name_en, "英語名" %><br>
    <%= f.text_field :name_en %>
  </div>

  <p>ジャンル</p>
  <%= render "form_game_genre", object: @game_info %>

  <p>プラットフォーム</p>
  <%= render "form_game_platform", object: @game_info %>

  <p>操作方法</p>
  <div id="register_new_controller_manual_form" style="display:none;">
	<p>新規操作方法登録</p>
	<%= hidden_field_tag "game_info[game_key_config_infos][][game_platform_id]", -1, {:id => 'game_key_configs_game_platform_id'} -%>
	<%= button_tag type: 'button', onclick: "window.open('/game_infos/register_new_game_action_form', '新規アクション登録', 'width=500,height=400')" do %>
		<%= "新規アクション登録" %>
	<% end %>
  </div>

  <% @game_info.game_key_configs.each do |key_config| %>
  <%= key_config.id %>
	  <% key_config.game_keys.each do |key| %>
	  <%= key.id %>
	  	<%= key.game_key_type.name_en %>
	  <% end %>
  <% end %>

  <div class="actions">
    <%= f.submit "新規作成" %>
  </div>

<% end %>

<div id="btn_register_new_controller_manual">
  	<% @game_info.game_platforms.each do |platform| %>
		<% next if GameKeyConfig.where(:game_platform_id => platform.id, :game_info_id => @game_info.id).blank? == false %>
		<%= form_tag('/game_infos/register_new_controller_manual', :remote => true, :method => 'get') do %>
			<%= hidden_field_tag :id, @game_info.id -%>
			<%= hidden_field_tag :game_platform_id, platform.id -%>
			<% button_name = "[#{platform.name_en}]新規操作方法登録" %>
			<% button_id = "register_new_controller_#{platform.name_en}" %>
			<%= submit_tag(button_name, :class => 'btn btn-primary btn-sm', :id => button_id) %>
		<% end %>
	<% end %>
</div>

app/views/game_infos/_form_game_genre.html.erb
<div class="field">
  <% if @game_info.game_genres == nil %>
  <%= select "game_info[game_genre_ids]", "", GameGenre.all.map { |c| [c.name_jp, c.id] }, :include_blank => true %>
  <% else %>
  <% @game_info.game_genres.each do |game_genre| %>
  <%= select "game_info[game_genre_ids]", "", [ [game_genre.name_jp, game_genre.id], ["", ""] ] %>
  <% end %>
  <%= select "game_info[game_genre_ids]", "", GameGenre.all.map { |c| [c.name_jp, c.id] }, :include_blank => true %>
  <% end %>
</div>

app/views/game_infos/_form_game_platform.html.erb
<div class="field">
  <% if @game_info.game_platforms == nil %>
<%
# ここ通らないかも
%>
	  <%= select "game_info[game_platform_ids]", "", GamePlatform.all.map { |c| [c.name_en, c.id] }, :include_blank => true %>
  <% else %>
	  <% @game_info.game_platforms.each do |game_platform| %>
		  <%= select "game_info[game_platform_ids]", "", [ [game_platform.name_en, game_platform.id], ["", ""] ] %>
	  <% end %>
	  <%= select "game_info[game_platform_ids]", "", GamePlatform.all.map { |c| [c.name_en, c.id] }, {:include_blank => true}, {:id => "game_platform_add"} %>
  <% end %>
</div>

app/views/game_infos/edit.html.erb
<h1>Editing Game Info</h1>

<%= render 'form' %>

<%= link_to 'Show', @game_info %> |
<%= link_to 'Back', game_infos_path %>

app/views/game_infos/index.html.erb
<% provide(:title, "GameDataBase") %>

<p id="notice"><%= notice %></p>

<h1>ゲームデータベース</h1>

<table>
  <thead>
    <tr>
      <th>Name jp</th>
      <th>Name en</th>
	  <th>ジャンル</th>
	  <th>プラットフォーム</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @game_infos.each do |game_info| %>
      <tr>
        <td><%= game_info.name_jp %></td>
        <td><%= game_info.name_en %></td>
		<td>
			<% if game_info.game_genres != nil %>
				<% game_info.game_genres.each do |game_genre| %>
				  <%= game_genre.name_jp if game_genre != nil %>
		  		<% end %>
		  <% end %>
		</td>
		<td>
			<% if game_info.game_platforms != nil %>
				<% game_info.game_platforms.each do |game_platform| %>
				  <%= game_platform.name_en if game_platform != nil %>
		  		<% end %>
		  <% end %>
		</td>
        <td><%= link_to 'Show', game_info %></td>
        <td><%= link_to 'Edit', edit_game_info_path(game_info) %></td>
        <td><%= link_to 'Destroy', game_info, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Game info', new_game_info_path %>

app/views/game_infos/new.html.erb
<h1>New Game Info</h1>

<%= render 'form' %>

<%= link_to 'Back', game_infos_path %>

app/views/game_infos/register_new_controller_manual.js.erb
$("#btn_register_new_controller_manual").hide()

var register_div = $("#register_new_controller_manual_form");
register_div.show();

$("#game_key_configs_game_platform_id").attr("value", "<%= @game_platform_id %>");

// 指定プラットフォームの各ボタン操作選択用のselectタグ配置
<% game_key_types = GameKeyType.where(:game_platform_id => @game_platform_id) %>
<% game_actions = GameAction.all() %>

register_div.append("<table id='register_new_controller_table'></table>")
var table_tag = $("#register_new_controller_table");

table_tag.append("<tr><th>ボタン名</th><th>操作</th></tr>");
<% game_key_types.each do |key_type| %>

   var line = $("<tr></tr>");
   line.append("<th><%= key_type.sign %></th>");

   // selectタグの内容全部一緒なのでeachで回す必要ないかも
   var select_tag = $("<select></select>", {
   	   			  	name: "game_info[game_key_config_infos][][<%= key_type.id %>]",
					id: "game_key_select"
   	   			  	});

   select_tag.append("<option value=\"\"></option>");

   <% game_actions.each do |game_action| %>
   	  select_tag.append( $("<option></option>", { value: "<%= game_action.id %>", html: "<%= game_action.name_jp %>" }) );
   <% end %>
   line.append( $("<th></th>").append(select_tag) );

   table_tag.append(line);
<% end %>

app/views/game_infos/register_new_game_action.js.erb
var select_tags = window.opener.$("#game_key_select");

for( var i=0; i < select_tags.length; i++ ){
	 select_tags.eq(i).append( $("<option></option>", { value: "<= @game_action.id %>", html: "<%= @game_action.name_jp %>" }) );
}

if( <%= @is_success %> == false ){
	alert("新規アクション登録失敗");
}

window.close();

app/views/game_infos/register_new_game_action_form.html.erb
<h1>新規アクション登録フォーム</h1>

<%= form_tag('register_new_game_action', :remote => true, :method => 'get') do %>
	<%= label "", "日本語名" %><%= text_field_tag :name_jp, "" %><br>
	<%= label "", "英語名　" %><%= text_field_tag :name_en, "" %><br>
	<%= submit_tag("新規アクション登録", :class => 'btn btn-primary btn-sm', :confirm => "新規アクションを登録しますか？") %>
<% end %>

app/views/game_infos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name jp:</strong>
  <%= @game_info.name_jp %>
</p>

<p>
  <strong>Name en:</strong>
  <%= @game_info.name_en %>
</p>

<div id='current_platform_field'>
  表示中のプラットフォーム:<span id='current_platform_field_value'></span>
</div>
<%
platforms = @game_info.game_platforms != nil ? @game_info.game_platforms : []
%>
<% platforms.each do |platform| %>
	<%= form_tag('/game_infos/switch_by_platform', :remote => true, :method => 'get') do %>
		<%= hidden_field_tag :id, @game_info.id -%>
		<%= hidden_field_tag :platform, platform.name_en -%>
		<%= submit_tag(platform.name_en, :class => 'btn btn-primary btn-sm') -%>
	<% end %>
<% end %>



<div id='div_game_key_config', style='display:none;'>
</div>



<%= link_to 'Edit', edit_game_info_path(@game_info) %> |
<%= link_to 'Back', game_infos_path %>

app/views/game_infos/switch_by_platform.js.erb
$("#current_platform_field_value").text("<%= @current_platform != nil ? @current_platform.name_en : "" %>")

var div_tag = $("#div_game_key_config");
div_tag.empty(); // テーブルの情報を一旦リセット
div_tag.show();

var table_tag = $("<table></table>");
table_tag.append( $("<th></th>", { html: "ボタン" }) );
table_tag.append( $("<th></th>", { html: "アクション" }) );
div_tag.append(table_tag);
<% 
   game_key_config = nil
   if @current_platform != nil
   	  game_key_config = GameKeyConfig.find_by(:game_info_id => @game_info.id, :game_platform_id => @current_platform.id)
   end
%>

<% if game_key_config != nil %>
	<% game_key_config.game_keys.each do |game_key| %>
	   <% game_key_type = GameKeyType.find(game_key.game_key_type_id) %>
	   <% game_action = GameAction.find(game_key.game_action_id) %>

	   var line = $("<tr></tr>");
	   line.append( $("<th></th>", { html: "<%= game_key_type.sign %>" }) );
	   line.append( $("<th></th>", { html: "<%= game_action.name_jp %>" }) );

	   table_tag.append(line);
	<% end %>
<% end %>